export const CREATE_CLASSIFIED = "CREATE_CLASSIFIED";
export const RETRIEVE_CLASSIFIEDS = "RETRIEVE_CLASSIFIEDS";
export const UPDATE_CLASSIFIED = "UPDATE_CLASSIFIED";
export const DELETE_CLASSIFIED = "DELETE_CLASSIFIED";
export const DELETE_ALL_CLASSIFIEDS = "DELETE_ALL_CLASSIFIEDS";